### ISSUE TITLE
fix: Fabric Texture Error

### ISSUE THREAD

**Issue by HassanTeslim007** [Yczar/textura#2]
**Description**
There's a red screen error when the Fabric Texture is clicked on

**Steps To Reproduce**

1. Scroll down to and Click on fabricTexture

**Expected Behavior**
A red Screen shows the error "type 'FabricTextureRenderObject' is not a subtype of type 'RenderObjectWithChildMixin<RenderObject>'
in type cast"

**Screenshots**
<img width="1440" alt="Screenshot 2023-10-28 at 09 23 37" src="https://github.com/Yczar/textura/assets/64636170/9264c305-7777-47c3-a7f6-e8ad9069330b">

**Additional Context**
Error has been encountered on MacOS and Android. Other platforms have not been tested

**Comment by Yczar** [comment]
Fixed here: #3
